# Generated by Django 3.1.1 on 2020-09-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsinnigeria', '0004_auto_20200918_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
